# Usa la imagen oficial de Node.js como base
FROM node:14-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /usr/src/app

# Copia los archivos de dependencias primero para aprovechar el cacheo de Docker
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install --silent

# Copia el resto del código de la aplicación
COPY . .

# Expone el puerto en el que corre la aplicación
EXPOSE 3001

# Comando por defecto para ejecutar la aplicación
CMD ["node", "app.js"]
