# Usa la imagen oficial de Node.js como base
FROM node:14-slim

# Crea el directorio de trabajo
WORKDIR /usr/src/app

# Copia package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install --silent

# Copia el código fuente
COPY . .

# Expone el puerto
EXPOSE 3000

# Comando para correr el servicio
CMD ["node", "app.js"]
